# Generated by Django 4.1.2 on 2022-10-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_romm_name_alter_amenity_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
