# Generated by Django 4.1.2 on 2022-10-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('price_per_night', models.PositiveIntegerField(help_text='정수만 가능합니다', verbose_name='Price')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=140)),
                ('pet_allowed', models.BooleanField(default=True, help_text='이 집은 애완동물을 허용하나요?', verbose_name='Pets Allowed?')),
            ],
        ),
    ]
