# Generated by Django 4.1.2 on 2022-10-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_pet_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='price',
            new_name='price_per_night',
        ),
    ]
