# Generated by Django 4.1.2 on 2022-10-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('experiences', '0002_rename_start_at_experiences_start_alter_perk_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
