# Generated by Django 4.1.2 on 2022-10-24 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0002_alter_category_options'),
        ('experiences', '0004_remove_perk_category_experiences_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiencess', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='perks',
            field=models.ManyToManyField(related_name='experiencess', to='experiences.perk'),
        ),
    ]
